version: "3.9"
services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8080
    volumes:
      - .:/app
    ports:
      - 8008:8080
    depends_on:
      - db
    env_file: .env
    networks:
      - backend
  db:
    image: bitnami/postgresql
    container_name: postgres_reservations
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
